USE beyond_the_feed;

UPDATE articles SET title = 'The Post-Post Instagram', slug = 'the-post-post-instagram', excerpt = 'How Instagram posting culture is moving from polished performance toward smaller, more honest audiences.', body = 'The pressure to make every Instagram post look like proof of a perfect life has softened. Photo dumps, quieter captions and Close Friends stories make room for the unfinished, the ordinary and the people who already know the context. The feed is still a stage, and comparison has not disappeared, but posting can now feel less like a performance review and more like choosing what is worth sharing.', read_time = '6 min read', source = 'Instagram', source_url = 'https://about.instagram.com/blog/announcements/instagram-ranking-explained', published_at = '2023-05-31', featured = TRUE, published = TRUE WHERE id = 1;
UPDATE articles SET title = 'Your Niche Is Already Here', slug = 'your-niche-is-already-here', excerpt = 'Reels, carousels and Instagram communities are turning small interests into places to learn, make and belong.', body = 'Instagram discovery can begin with a Reel, continue through a carousel and end in a page devoted to an interest you did not know had a community. That path can become a rabbit hole, but it can also introduce a beginner to a creative practice, a collaborator or a language for something they already love. The useful question is whether the algorithm keeps us watching or helps us take part.', read_time = '8 min read', source = 'Instagram', source_url = 'https://about.instagram.com/blog/announcements/instagram-ranking-explained', published_at = '2023-05-31', featured = FALSE, published = TRUE WHERE id = 2;
UPDATE articles SET title = 'The Link in Bio Is a Business Model', slug = 'the-link-in-bio-is-a-business-model', excerpt = 'How Instagram helps creators and small businesses turn discovery, collaborations and visual storytelling into a storefront.', body = 'For a small business or independent creator, Instagram can be a shop window, portfolio and first conversation in one place. A Reel can introduce the process, a carousel can answer a customer question and a collaboration can bring two communities together. The platform does not remove the work of building a sustainable business, but it can make a point of view discoverable before a brand has the budget for a physical storefront.', read_time = '7 min read', source = 'Instagram', source_url = 'https://about.instagram.com/blog/announcements/instagram-ranking-explained', published_at = '2023-05-31', featured = FALSE, published = TRUE WHERE id = 3;
UPDATE articles SET title = 'A Feed You Can Live With', slug = 'a-feed-you-can-live-with', excerpt = 'How intentional scrolling, private sharing and Instagram safety controls can lower the pressure to be always on.', body = 'A healthier Instagram practice starts with deciding what the app is for. Follow accounts that teach or delight you, use private sharing when a moment belongs to a smaller circle, and take a break when the feed turns comparison into background noise. Instagram has introduced controls intended to make experiences more age-appropriate and manageable, but the most useful boundary is still the one that leaves enough attention for life away from the screen.', read_time = '6 min read', source = 'Meta Newsroom', source_url = 'https://about.fb.com/news/2024/01/teen-protections-age-appropriate-experiences-on-our-apps/', published_at = '2024-01-09', featured = FALSE, published = TRUE WHERE id = 4;

-- Preserve legacy rows and any comments while keeping the public collection at four articles.
UPDATE articles SET published = FALSE WHERE id > 4;
