CREATE DATABASE IF NOT EXISTS beyond_the_feed CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE beyond_the_feed;

CREATE TABLE categories (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) NOT NULL UNIQUE, slug VARCHAR(100) NOT NULL UNIQUE, description VARCHAR(255));
CREATE TABLE users (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(120) NOT NULL, email VARCHAR(180) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, role ENUM('READER','EDITOR','ADMIN') NOT NULL DEFAULT 'READER', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE articles (id INT PRIMARY KEY AUTO_INCREMENT, category_id INT NOT NULL, author_id INT NULL, title VARCHAR(220) NOT NULL, slug VARCHAR(240) NOT NULL UNIQUE, excerpt TEXT NOT NULL, body TEXT NOT NULL, image_url VARCHAR(500), read_time VARCHAR(30), source VARCHAR(120), source_url VARCHAR(500), published_at DATE, featured BOOLEAN NOT NULL DEFAULT FALSE, published BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT fk_article_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT, CONSTRAINT fk_article_author FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE comments (id INT PRIMARY KEY AUTO_INCREMENT, article_id INT NOT NULL, user_id INT NULL, body TEXT NOT NULL, approved BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_comment_article FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE CASCADE, CONSTRAINT fk_comment_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL);

SET @add_source = (SELECT IF(EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'articles' AND column_name = 'source'), 'SELECT 1', 'ALTER TABLE articles ADD COLUMN source VARCHAR(120)'));
PREPARE add_source_statement FROM @add_source; EXECUTE add_source_statement; DEALLOCATE PREPARE add_source_statement;
SET @add_source_url = (SELECT IF(EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'articles' AND column_name = 'source_url'), 'SELECT 1', 'ALTER TABLE articles ADD COLUMN source_url VARCHAR(500)'));
PREPARE add_source_url_statement FROM @add_source_url; EXECUTE add_source_url_statement; DEALLOCATE PREPARE add_source_url_statement;
SET @add_published_at = (SELECT IF(EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'articles' AND column_name = 'published_at'), 'SELECT 1', 'ALTER TABLE articles ADD COLUMN published_at DATE'));
PREPARE add_published_at_statement FROM @add_published_at; EXECUTE add_published_at_statement; DEALLOCATE PREPARE add_published_at_statement;

INSERT INTO categories (name, slug, description) VALUES ('Instagram & The Mind','mind','Comparison, attention, self-expression and the inspiration we find in a shared visual world.'),('Creativity & Communities','creativity','Creators, niche communities and the collaborations that make discovery feel human.'),('Instagram for Business','business','How small businesses and independent creators turn a feed into a digital storefront.'),('Healthy Digital Habits','habits','Mindful scrolling, intentional use and boundaries for a healthier relationship with the feed.');
INSERT INTO users (name,email,password_hash,role) VALUES ('Maya Chen','maya@beyondthefeed.com','demo-hash','EDITOR'),('Noah Williams','noah@beyondthefeed.com','demo-hash','EDITOR'),('Ari Okafor','ari@beyondthefeed.com','demo-hash','EDITOR'),('Lena Ortiz','lena@beyondthefeed.com','demo-hash','EDITOR');
INSERT INTO articles (category_id,author_id,title,slug,excerpt,body,image_url,read_time,featured) VALUES
(1,1,'The Post-Post Instagram','the-post-post-instagram','How Instagram posting culture is moving from polished performance toward smaller, more honest audiences.','The pressure to make every Instagram post look like proof of a perfect life has softened. Photo dumps, quieter captions and Close Friends stories make room for the unfinished, the ordinary and the people who already know the context. The feed is still a stage, and comparison has not disappeared, but posting can now feel less like a performance review and more like choosing what is worth sharing.','https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=1200&q=85','6 min read',TRUE),
(2,3,'Your Niche Is Already Here','your-niche-is-already-here','Reels, carousels and Instagram communities are turning small interests into places to learn, make and belong.','Instagram discovery can begin with a Reel, continue through a carousel and end in a page devoted to an interest you did not know had a community. That path can become a rabbit hole, but it can also introduce a beginner to a creative practice, a collaborator or a language for something they already love. The useful question is whether the algorithm keeps us watching or helps us take part.','https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=900&q=85','8 min read',FALSE),
(3,4,'The Link in Bio Is a Business Model','the-link-in-bio-is-a-business-model','How Instagram helps creators and small businesses turn discovery, collaborations and visual storytelling into a storefront.','For a small business or independent creator, Instagram can be a shop window, portfolio and first conversation in one place. A Reel can introduce the process, a carousel can answer a customer question and a collaboration can bring two communities together. The platform does not remove the work of building a sustainable business, but it can make a point of view discoverable before a brand has the budget for a physical storefront.','https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=900&q=85','7 min read',FALSE),
(4,1,'A Feed You Can Live With','a-feed-you-can-live-with','How intentional scrolling, private sharing and Instagram safety controls can lower the pressure to be always on.','A healthier Instagram practice starts with deciding what the app is for. Follow accounts that teach or delight you, use private sharing when a moment belongs to a smaller circle, and take a break when the feed turns comparison into background noise. Instagram has introduced controls intended to make experiences more age-appropriate and manageable, but the most useful boundary is still the one that leaves enough attention for life away from the screen.','https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=900&q=85','6 min read',FALSE);

UPDATE articles SET source = 'Instagram', source_url = 'https://about.instagram.com/blog/announcements/instagram-ranking-explained', published_at = '2023-05-31' WHERE id IN (1, 2, 3);
UPDATE articles SET source = 'Meta Newsroom', source_url = 'https://about.fb.com/news/2024/01/teen-protections-age-appropriate-experiences-on-our-apps/', published_at = '2024-01-09' WHERE id = 4;
